spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        ## service1
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        ## Service2
        - id: HOTEL-SERVICE
          uri: lb://sHOTEL-SERVICE
          predicates:
            - Path=/api/v1/hotels/**


        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**

server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka